### ISSUE TITLE
Reprocessing

### ISSUE THREAD

**Issue by brianjgeiger** [samchrisinger/osf_md_test#2]
I think it would be good to separate the acquisition of the markdown files from the processing and diffing. That way, when we have all the data off the OSF, we can just make changes to the JS renderer and see how that affects the diffs, and not have to make more requests to the OSF.

**Comment by samchrisinger** [comment]
See: https://github.com/samchrisinger/osf_md_test/commit/c756ca8bc7074f9cf7e1167f805ccfe4ef72e220
